[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
check_di_registry = "9sNDitEeYSFQ7LxmNuaiZPoCLVdrzhdR8P5zmoEW78Yi"

[provider]
cluster = "devnet"
wallet = "~/GitHub/check-di/.data/devnet-pow-keypair.json"

[workspace]
members = ["programs/check_di_registry"]

[hooks]
